### ISSUE TITLE
Error message on failed workspace deployment not visible in the UI

### ISSUE THREAD

**Issue by javos79** [microsoft/AzureTRE#3257] opened 2023-02-27 12:56 UTC
Error messages are not visible when deploying on a workspace level as we could not access a failed workspace, hence, we could not access the operations tab. 

As a result, we have to query the cosmos database manually, filtering by workspace ID which is also time consuming.

**Comment by marrobi** [comment] 2023-02-27 14:51
Closing as duplicate of https://github.com/microsoft/AzureTRE/issues/2363 which should picked up in the next few weeks.

The operation logs can be retrieved without accessing Cosmos DB by using the Swagger UI for the API.

![image](https://user-images.githubusercontent.com/17089773/221596274-14c0eda2-3c5b-4c73-b20d-a1865914e6c1.png)

**Closed by marrobi** 2023-02-27 14:51 UTC
Labels: bug
