### ISSUE TITLE
Airlock - Add Airlock Audit Logging

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#2275] opened 2022-07-16 19:40 UTC
## Description

As a TRE Developer
I want to add a new endpoint so reviewers can add intermidiate 'virtual' steps
So that the review process can have more steps and reviewers will be able to write comments

## Acceptance criteria

- [ ] Add new api
- [ ] all comments are stored in the review object in cosmos

**Comment by tamirkamara** [comment] 2022-07-17 13:22
@eladiw it this a duplicate of https://github.com/microsoft/AzureTRE/issues/2070?

**Comment by joalmeid** [comment] 2022-07-20 09:20
@marrobi , please refine this issue

**Comment by tamirkamara** [comment] 2022-09-05 19:33
duplicate

**Closed by tamirkamara** 2022-09-05 19:33 UTC
Labels: story, airlock
