### ISSUE TITLE
Unverified HTTPS request is being made to Cosmos.

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/AzureTRE#1997] opened 2022-06-08 12:30 UTC
**Describe the bug**
Unverified HTTPS request is being made to Cosmos. This is from the API App to Cosmos - it could be the tests.

```
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cosmos-ross1-westeurope.documents.azure.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
```

**Steps to reproduce**

1. Look in the `AppServiceConsoleLogs` in Log Analytics.

**Comment by tamirkamara** [comment] 2022-06-08 13:27
It's not just the tests, happens also in the apps themselves...

**Comment by marrobi** [comment] 2022-08-03 07:51
Closing as duplicate of #1877

**Closed by marrobi** 2022-08-03 07:51 UTC
Labels: bug
