### ISSUE TITLE
is it possible to access internet in base work space ?

### ISSUE THREAD

**Issue by basitrehman531997** [microsoft/AzureTRE#3709] opened 2023-09-11 14:55 UTC
1.i create guacamole service in base workspace which have not internet
in guacamole service   window 10 ,11, data science and Linux vms also have no access  to internet

**Comment by tamirkamara** [comment] 2023-09-12 18:31
The main idea of this solution is to limit internet access to reduce the risk of data exfiltration. 
However, there're ways to do this and probably the simplest is to use the _unrestricted_ workspace to allow all resource in the workspace to access any internet address.

**Comment by marrobi** [comment] 2023-09-22 09:27
Closing this as by design, and unrestricted provides example how to allow.

**Closed by marrobi** 2023-09-22 09:27 UTC
Labels: question
