### ISSUE TITLE
[BUG] Quickstart is missing auth configuration details

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#402] opened 2021-06-30 21:40 UTC
**Describe the bug**
The solution required environment settings to be configured for auth:

```
# Auth configuration
AAD_TENANT_ID=__CHANGE_ME__
API_CLIENT_ID=__CHANGE_ME__
API_CLIENT_SECRET=__CHANGE_ME__
SWAGGER_UI_CLIENT_ID=__CHANGE_ME__
```

These are omitted from the quickstart. What steps do I need to follow?

In addition these variables are defined when provisioning the management infrastructure `devops/.env.sample` , when they should be defined with the core TRE infrastructure  `templates/core/.env.sample` as they may be different for each TRE environment.

**Comment by christoferlof** [comment] 2021-07-01 08:25
Duplicate of #378 . Closing this one.

**Closed by christoferlof** 2021-07-01 08:25 UTC
Labels: bug
