### ISSUE TITLE
Nexus shared service Update dialog doesn't populate SSL cert name

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3697] opened 2023-08-31 18:59 UTC
**Describe the bug**
When trying to update the Nexus shared service, the cert name text box is blank and disabled.

Clicking Submit results in an error message.

**Steps to reproduce**

1. Deploy Nexus.
1. Click **Update**.
1. Click **Submit**.

**Comment by marrobi** [comment] 2023-09-21 08:13
@SvenAelterman found an issue - https://github.com/microsoft/AzureTRE/issues/3716

**Comment by marrobi** [comment] 2023-09-21 09:23
Fixed in https://github.com/microsoft/AzureTRE/pull/3717

**Comment by marrobi** [comment] 2023-09-21 14:16
Closing this as duplicate of #3717

**Closed by marrobi** 2023-09-21 14:16 UTC
Labels: bug
