### ISSUE TITLE
Getting a 502 when restarting with `make start`

### ISSUE THREAD

**Issue by t-young31** [microsoft/AzureTRE#2879] opened 2022-11-15 11:26 UTC
**Describe the bug**
We're getting 502 Bad Gateway errors when trying to access the web app after a `make stop`-`make start`. Restarting the app service fixes it immediately.

**Steps to reproduce**

This might be tricky as it seems to have arisen without anything changing in our deployment.

**Comment by t-young31** [comment] 2022-11-17 14:07
didn't happen today so going to close this for the time being. It doesn't feel like an easy fix

**Comment by javos79** [comment] 2023-02-10 15:35
We faced this problem a couple of times since we installed TRE. 
But we still don't know the root cause. 

Is there a solution for this or something to avoid?

**Comment by marrobi** [comment] 2023-02-10 16:05
@javos79 does this only happen after running `make tre-stop` followed by `make tre-start`

I believe it could be an app gateway caching issue.

What de the API logs say ( https://microsoft.github.io/AzureTRE/0.8.0/troubleshooting-faq/api-logs-deployment-center/ )?

Also be interested what a test in the app gateway health probe gives - edit the custom probe and click test https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-create-probe-portal#test-backend-health-with-the-probe (as this avoids caching)

**Comment by marrobi** [comment] 2023-02-20 08:59
@javos79 @t-young31 If you have a reoccurrence of this can you please let me know what the steps above show, especially the app gateway health probe.

Thanks.

**Comment by javos79** [comment] 2023-02-23 08:36
Here the screen shot of the health probe

<img width="913" alt="image" src="https://user-images.githubusercontent.com/46265242/220855849-fdedead1-f2a8-4b49-85fd-3674eff4d420.png">

and attached the log file 

[AppService-api-____tredev2-log-502-504.txt](https://github.com/microsoft/AzureTRE/files/10811642/AppService-api-____tredev2-log-502-504.txt)

**Comment by t-young31** [comment] 2023-02-23 08:51
seems to have stopped for us after the upgrade to v0.9

**Comment by marrobi** [comment] 2023-10-25 14:24
We've not seen this for a while. So closing.

**Closed by marrobi** 2023-10-25 14:24 UTC
Labels: bug
