### ISSUE TITLE
[Task] Create E2E tests for workspace service

### ISSUE THREAD

**Issue by LizaShak** [microsoft/AzureTRE#830] opened 2021-09-13 11:32 UTC
Story: #623 

**Description**
Add an E2E for deploying a workspace-service, validating that it is deployed and updated successfully. Disabled and deleted at the end.

**Comment by TessFerrandez** [comment] 2021-09-15 12:38
Per todays daily, this is a duplicate of #643 that @msebragge already has a PR for - so closing this as dupe

**Closed by TessFerrandez** 2021-09-15 12:38 UTC
