### ISSUE TITLE
Support for GitHub environment variables instead of secrets

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/AzureTRE#3403] opened 2023-04-02 16:59 UTC
## Description

As a TRE Administrator
I want to use GitHub environment variables instead of secrets to store non-sensitive data
So that it's easier to review the configuration of a repo.

I think this list of secrets should be turned into variables instead:

- TRE_ID
- LOCATION
- MGMT_RESOURCE_GROUP_NAME
- MGMT_STORAGE_ACCOUNT_NAME
- ACR_NAME
- CORE_ADDRESS_SPACE
- TRE_ADDRESS_SPACE
- TERRAFORM_STATE_CONTAINER_NAME
- CORE_APP_SERVICE_PLAN_SKU
- WORKSPACE_APP_SERVICE_PLAN_SKU
- RESOURCE_PROCESSOR_NUMBER_PROCESSES_PER_INSTANCE
- ENABLE_SWAGGER

## Acceptance criteria

- [ ] CI/CD GitHub Actions (yml) updated to use variables instead of secrets
- [ ] Instructions updated

**Comment by tamirkamara** [comment] 2023-04-03 06:25
Duplicate of https://github.com/microsoft/AzureTRE/issues/3070

**Closed** 2023-04-04 13:19 UTC
Labels: story
