### ISSUE TITLE
Manually deleting TRE VMs?

### ISSUE THREAD

**Issue by jonnyry** [microsoft/AzureTRE#4165] opened 2024-12-05 11:55 UTC
A number of unused VMs won't delete through the TRE GUI, due to various errors thrown by Terraform - one of them is shown below.

What is the correct mechanism to manually delete a VM running under the TRE?

_57fb6bd6-4158-42ca-861c-f89228f42f18: Error message: uninstalling bundle [31m╷[0m[0m [31m│[0m [0m[1m[31mError: [0m[0m[1mpowering off Windows Virtual Machine (Subscription: "*******" [31m│[0m [0mResource Group Name: "rg-*******-ws-9e0d" [31m│[0m [0mVirtual Machine Name: "windowsvm2f18"): performing PowerOff: unexpected status 409 (409 Conflict) with error: OperationNotAllowed: Operation 'powerOff' is not allowed on VM 'windowsvm2f18' since the VM is either deallocated or marked to be deallocated. Please refer to https://aka.ms/vmpowerstates to learn about different VM power states.[0m [31m│[0m [0m [31m│[0m [0m[0m [31m╵[0m[0m error running command /cnab/app/terraform /usr/bin/terraform destroy -auto-approve -input=false -var image=Windows 10 -var image_gallery_id= -var parent_service_id=c10744de-5143-474e-9d81-3df14ea4fbab -var shared_storage_access=true -var shared_storage_name=vm-shared-storage -var tre_id=******* -var tre_resource_id=57fb6bd6-4158-42ca-861c-f89228f42f18 -var vm_size=2 CPU | 8GB RAM -var workspace_id=2dd8fefc-34eb-4bc5-a19f-062034909e0d: exit status 1 Error: error running command /cnab/app/terraform /usr/bin/terraform destroy -auto-approve -input=false -var image=Windows 10 -var image_gallery_id= -var parent_service_id=c10744de-5143-474e-9d81-3df14ea4fbab -var shared_storage_access=true -var shared_storage_name=vm-shared-storage -var tre_id=******* -var tre_resource_id=57fb6bd6-4158-42ca-861c-f89228f42f18 -var vm_size=2 CPU | 8GB RAM -var workspace_id=2dd8fefc-34eb-4bc5-a19f-062034909e0d: exit status 1 1 error occurred: * mixin execution failed: package command failed /cnab/app/cnab/app/mixins/terraform/runtimes/terraform-runtime uninstall [31m╷[0m[0m [31m│[0m [0m[1m[31mError: [0m[0m[1mpowering off Windows Virtual Machine (Subscription: *******" [31m│[0m [0mResource Group Name: "rg-*******-ws-9e0d" [31m│[0m [0mVirtual Machine Name: "windowsvm2f18"): performing PowerOff: unexpected status 409 (409 Conflict) with error: OperationNotAllowed: Operation 'powerOff' is not allowed on VM 'windowsvm2f18' since the VM is either deallocated or marked to be deallocated. Please refer to https://aka.ms/vmpowerstates to learn about different VM power states.[0m [31m│[0m [0m [31m│[0m [0m[0m [31m╵[0m[0m error running command /cnab/app/terraform /usr/bin/terraform destroy -auto-approve -input=false -var image=Windows 10 -var image_gallery_id= -var parent_service_id=c10744de-5143-474e-9d81-3df14ea4fbab -var shared_storage_access=true -var shared_storage_name=vm-shared-storage -var tre_id=******* -var tre_resource_id=57fb6bd6-4158-42ca-861c-f89228f42f18 -var vm_size=2 CPU | 8GB RAM -var workspace_id=2dd8fefc-34eb-4bc5-a19f-062034909e0d: exit status 1 Error: error running command /cnab/app/terraform /usr/bin/terraform destroy -auto-approve -input=false -var image=Windows 10 -var image_gallery_id= -var parent_service_id=c10744de-5143-474e-9d81-3df14ea4fbab -var shared_storage_access=true -var shared_storage_name=vm-shared-storage -var tre_id=******* -var tre_resource_id=57fb6bd6-4158-42ca-861c-f89228f42f18 -var vm_size=2 CPU | 8GB RAM -var workspace_id=2dd8fefc-34eb-4bc5-a19f-062034909e0d: exit status 1 1 error occurred: * mixin execution failed: package command failed /cnab/app/cnab/app/mixins/terraform/runtimes/terraform-runtime uninstall [31m╷[0m[0m [31m│[0m [0m[1m[31mError: [0m[0m[1mpowering off Windows Virtual Machine (Subscription: *******" [31m│[0m [0mResource Group Name: "rg-*******-ws-9e0d" [31m│[0m [0mVirtual Machine Name: "windowsvm2f18"): performing PowerOff: unexpected status 409 (409 Conflict) with error: OperationNotAllowed: Operation 'powerOff' is not allowed on VM 'windowsvm2f18' since the VM is either deallocated or marked to be deallocated. Please refer to https://aka.ms/vmpowerstates to learn about different VM power states.[0m [31m│[0m [0m [31m│[0m [0m[0m [31m╵[0m[0m error running command /cnab/app/terraform /usr/bin/terraform destroy -auto-approve -input=false -var image=Windows 10 -var image_gallery_id= -var parent_service_id=c10744de-5143-474e-9d81-3df14ea4fbab -var shared_storage_access=true -var shared_storage_name=vm-shared-storage -var tre_id=******* -var tre_resource_id=57fb6bd6-4158-42ca-861c-f89228f42f18 -var vm_size=2 CPU | 8GB RAM -var workspace_id=2dd8fefc-34eb-4bc5-a19f-062034909e0d: exit status 1 Error: error running command /cnab/app/terraform /usr/bin/terraform destroy -auto-approve -input=false -var image=Windows 10 -var image_gallery_id= -var parent_service_id=c10744de-5143-474e-9d81-3df14ea4fbab -var shared_storage_access=true -var shared_storage_name=vm-shared-storage -var tre_id=******* -var tre_resource_id=57fb6bd6-4158-42ca-861c-f89228f42f18 -var vm_size=2 CPU | 8GB RAM -var workspace_id=2dd8fefc-34eb-4bc5-a19f-062034909e0d: exit status 1 1 error occurred: * container exit code: 1, message: <nil> ; Command executed: porter uninstall "57fb6bd6-4158-42ca-861c-f89228f42f18" --reference *******acr.azurecr.io/tre-service-guacamole-windowsvm:v1.0.1 --param arm_environment="public" --param arm_use_msi="true" --param azure_environment="AzureCloud" --param id="57fb6bd6-4158-42ca-861c-f89228f42f18" --param os_image="Windows 10" --param parent_service_id="c10744de-5143-474e-9d81-3df14ea4fbab" --param shared_storage_access="True" --param tfstate_container_name="tfstate" --param tfstate_resource_group_name="rg-*******-mgmt" --param tfstate_storage_account_name="*******mgmtstore" --param tre_id="*******" --param workspace_id="2dd8fefc-34eb-4bc5-a19f-062034909e0d" --force --credential-set arm_auth --credential-set aad_auth_

**Comment by marrobi** [comment] 2024-12-05 11:59
This looks like a duplicate of https://github.com/microsoft/AzureTRE/issues/4135

I'll close this issue and lets track/discuss this there.

**Closed by marrobi** 2024-12-05 11:59 UTC
Labels: question
