### ISSUE TITLE
Guacamole E2E tests are stuck on HTTP 302

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#1602] opened 2022-03-27 06:11 UTC
**Describe the bug**
Accessing the Guacamole endpoint in the E2E always returns HTTP 302 - a redirect to log-in probably, which means that the credentials are not setup correctly?

**Steps to reproduce**
https://github.com/microsoft/AzureTRE/runs/5688108537?check_suite_focus=true

**Comment by daltskin** [comment] 2022-03-28 13:37
@joalmeid ok  to close?

**Comment by LizaShak** [comment] 2022-03-30 08:30
Depends on [story](https://github.com/microsoft/AzureTRE/issues/1386). We should test this once we have the access token  from proxy.

**Comment by anatbal** [comment] 2022-04-04 09:34
The source for this behavior is the corrupted guacamole image. for some reason, guacamole never seems to be up and running since the docker image fails on this error: "/usr/bin/env: 'sh\r': no such file or directory". Can be easily reproduced locally as well

**Comment by marrobi** [comment] 2022-04-04 09:38
Are you sure thats not just from the machine you built the image on rather than in the repo? Looks to me like Windows has changed the line endings to to CRLF from LF.

**Comment by anatbal** [comment] 2022-04-04 16:37
I also see this error on the webapp logs, and by locally I mean I still run the container which is Linux based

**Comment by marrobi** [comment] 2022-04-04 16:40
Does anybody else see this issue? 

We have seen this error when the code is checked out to a Windows file system and the line endings have been changed. Then when you build the image its corrupt. But only when built from your machine.

**Comment by anatbal** [comment] 2022-04-04 17:35
Perhaps a malformed version was merged into main? It happened when I did a clean make all and deployed a new Guacamole
@tamirkamara maybe worth checking on a mac?

**Comment by joalmeid** [comment] 2022-04-28 14:51
Can we re-check if this issue can still occur?

**Closed** 2022-07-27 08:51 UTC
Labels: bug
