### ISSUE TITLE
Multi step pipeline failed on step 741c7ff2-eff5-47b2-bf62-2b410d65c96b

### ISSUE THREAD

**Issue by martysharkey** [microsoft/AzureTRE#2891] opened 2022-11-16 15:20 UTC
We're having some issues with the workspaces being created. This is a brand new deployment within a dedicated Azure Subscription/Tenant. We have successfully deployed the base configuration and the update worked, its just when we deploy the workspaces that we get the updating_failed error. 

Resource Id
: 467e7b19-9fac-4481-bd1c-e349f9edff4d
Resource Path
: /workspaces/7c769b3f-6c33-4b32-b7a5-8f117bafc811/workspace-services/467e7b19-9fac-4481-bd1c-e349f9edff4d
Resource Version
: 3
Status
: updating_failed
Action
: upgrade
Message
: Multi step pipeline failed on step 741c7ff2-eff5-47b2-bf62-2b410d65c96b
Created
: Wed Nov 16 2022 11:00:38 GMT+0000 (4 hours ago)
Updated
: Wed Nov 16 2022 11:01:00 GMT+0000 (4 hours ago)
User
: removed

**Comment by marrobi** [comment] 2022-11-17 21:39
@ssalawu they all seemed to have failed with similar errors:

```
Error: Resource Group \"rg-cktre01-ws-c811\" was not found
```

That resource group should be created when the workspace is created. Can you verify that it exists in your subscription? If it does not exist then we need to look at the workspace deployment locs.

Can you retrieve the full workspace logs via the operations endpoint. This isn't something I've come across before - if the workspace has deployed successfully is there any way the resource group could have been deleted?

**Comment by marrobi** [comment] 2022-12-09 09:56
@tamirkamara @LizaShak  think this could have been caused by the clean validation environments workflow in the deployment repo?

Does we do something like loke for "tre" in a resource group name?!

**Comment by marrobi** [comment] 2022-12-16 14:28
We believe the disappearing resource groups might have been caused by one of the workflows in the deployment repo, and fixed by https://github.com/microsoft/AzureTRE-Deployment/pull/39

If further issues let us know. Thanks.

**Closed by marrobi** 2022-12-16 14:28 UTC
