### ISSUE TITLE
App registration's redirect url should be set automatically when creating a workspace

### ISSUE THREAD

**Issue by eladiw** [microsoft/AzureTRE#1352] opened 2022-02-21 13:11 UTC
## Description

As a TRE Workspace Owner/Azure TRE Developer
I want the redirect url to be set automatically in the app registration
So that I won't need this manual step before I can use services such as Guacamole

## Acceptance criteria

- [ ] When creating a new WS, the app registration for guacamole can be determined and set, automatically
- [ ] Either in the script or using the RP 
- [ ] Design is needed as part of this user story
- [ ] ~~#220 will add the AAD Application automatically when the workspace is created.~~

**Comment by joalmeid** [comment] 2022-03-14 16:01
Duplicate of #1096

**Comment by martinpeck** [comment] 2022-04-27 08:47
@ross-p-smith  to add a few dependencies and details

**Closed** 2022-06-24 06:03 UTC
Labels: design, story
