### ISSUE TITLE
Test creation of user resource as part of the E2E tests

### ISSUE THREAD

**Issue by anatbal** [microsoft/AzureTRE#1643] opened 2022-04-04 09:37 UTC
Add the user_resource creation process as tests in the e2e tests.
duplicate of #831

**Comment by marrobi** [comment] 2022-05-26 08:32
@anatbal if this is duplicate of #831, why was it reopened? Thanks.

**Comment by joalmeid** [comment] 2022-06-30 08:32
Confirmed with Anat. Duplicate of #831

**Closed by joalmeid** 2022-06-30 08:32 UTC
Labels: story
