### ISSUE TITLE
Error: waiting Firewall Policy Rule Collection Group "rcg-core"

### ISSUE THREAD

**Issue by Danny-Cooke-CK** [microsoft/AzureTRE#3775] opened 2023-11-04 13:23 UTC
Deployment of firewall fails on a new fresh deployment of TRE. 

The error of interest appears to be this one:- 
Error message: Unable to find image '***.azurecr.io/tre-shared-service-firewall@sha256:47de4b8b5b23fadbc82856ba6f14dfd410cf32eb4c089d2c15e31ca8040d2b7c' locally ╷ │ 
Error: waiting Firewall Policy Rule Collection Group "rcg-core"

Full error output below:-  
5468f7b2-9bfb-4589-9e7c-d6224b3e4493  deployment_failed  install   /shared-services/11336b4d-f3f3-4dc1-84cc-41e5cdc23a19  11336b4d-f3f3-4dc1-84cc-41e5cdc23a19: 
Error message: Unable to find image '***.azurecr.io/tre-shared-service-firewall@sha256:47de4b8b5b23fadbc82856ba6f14dfd410cf32eb4c089d2c15e31ca8040d2b7c' locally ╷ │ 
Error: waiting Firewall Policy Rule Collection Group "rcg-core" (Resource Group "rg-***" / Policy: "fw-policy-***"): Code="FirewallPolicyUpdateFailed" Message="Put on Firewall Policy fw-policy-*** Failed with 1 faulted referenced firewalls" │  │   with azurerm_firewall_policy_rule_collection_group.core, │   on rules.tf line 1, in resource "azurerm_firewall_policy_rule_collection_group" "core": │    1: resource "azurerm_firewall_policy_rule_collection_group" "core" *** │  ╵ 
error running command /cnab/app/terraform /usr/bin/terraform apply -auto-approve -input=false -var api_driven_network_rule_collections_b64=W10= -var api_driven_rule_collections_b64=W10= -var microsoft_graph_fqdn=graph.microsoft.com -var sku_tier=Standard -var tre_id=*** -var tre_resource_id=11336b4d-f3f3-4dc1-84cc-41e5cdc23a19: exit status 1 Error: 
error running command /cnab/app/terraform /usr/bin/terraform apply -auto-approve -input=false -var api_driven_network_rule_collections_b64=W10= -var api_driven_rule_collections_b64=W10= -var microsoft_graph_fqdn=graph.microsoft.com -var sku_tier=Standard -var tre_id=*** -var tre_resource_id=11336b4d-f3f3-4dc1-84cc-41e5cdc23a19: exit status 1 1 
error occurred: 	* mixin execution failed: package command failed /cnab/app/cnab/app/mixins/terraform/runtimes/terraform-runtime install ╷ │ 
Error: waiting Firewall Policy Rule Collection Group "rcg-core" (Resource Group "rg-***" / Policy: "fw-policy-***"): Code="FirewallPolicyUpdateFailed" Message="Put on Firewall Policy fw-policy-*** Failed with 1 faulted referenced firewalls" │  │   with azurerm_firewall_policy_rule_collection_group.core, │   on rules.tf line 1, in resource "azurerm_firewall_policy_rule_collection_group" "core": │    1: resource "azurerm_firewall_policy_rule_collection_group" "core" *** │  ╵ 
error running command /cnab/app/terraform /usr/bin/terraform apply -auto-approve -input=false -var api_driven_network_rule_collections_b64=W10= -var api_driven_rule_collections_b64=W10= -var microsoft_graph_fqdn=graph.microsoft.com -var sku_tier=Standard -var tre_id=*** -var tre_resource_id=11336b4d-f3f3-4dc1-84cc-41e5cdc23a19: exit status 1 Error: 
error running command /cnab/app/terraform /usr/bin/terraform apply -auto-approve -input=false -var api_driven_network_rule_collections_b64=W10= -var api_driven_rule_collections_b64=W10= -var microsoft_graph_fqdn=graph.microsoft.com -var sku_tier=Standard -var tre_id=*** -var tre_resource_id=11336b4d-f3f3-4dc1-84cc-41e5cdc23a19: exit status 1    1 
error occurred: 	* mixin execution failed: package command failed /cnab/app/cnab/app/mixins/terraform/runtimes/terraform-runtime install ╷ │ 
Error: waiting Firewall Policy Rule Collection Group "rcg-core" (Resource Group "rg-***" / Policy: "fw-policy-***"): Code="FirewallPolicyUpdateFailed" Message="Put on Firewall Policy fw-policy-*** Failed with 1 faulted referenced firewalls" │  │   with azurerm_firewall_policy_rule_collection_group.core, │   on rules.tf line 1, in resource "azurerm_firewall_policy_rule_collection_group" "core": │    1: resource "azurerm_firewall_policy_rule_collection_group" "core" *** │  ╵ 
error running command /cnab/app/terraform /usr/bin/terraform apply -auto-approve -input=false -var api_driven_network_rule_collections_b64=W10= -var api_driven_rule_collections_b64=W10= -var microsoft_graph_fqdn=graph.microsoft.com -var sku_tier=Standard -var tre_id=*** -var tre_resource_id=11336b4d-f3f3-4dc1-84cc-41e5cdc23a19: exit status 1 Error: 
error running command /cnab/app/terraform /usr/bin/terraform apply -auto-approve -input=false -var api_driven_network_rule_collections_b64=W10= -var api_driven_rule_collections_b64=W10= -var microsoft_graph_fqdn=graph.microsoft.com -var sku_tier=Standard -var tre_id=*** -var tre_resource_id=11336b4d-f3f3-4dc1-84cc-41e5cdc23a19: exit status 1    1 
error occurred: 	* container exit code: 1, message: <nil>   ; Command executed: az cloud set --name AzureCloud && az login --identity -u cb711806-1c70-4803-a83d-be084f044f7b && az acr login --name *** && porter install "11336b4d-f3f3-4dc1-84cc-41e5cdc23a19" --reference ***.azurecr.io/tre-shared-service-firewall:v1.1.5  --param arm_environment="public" --param arm_use_msi="true" --param id="11336b4d-f3f3-4dc1-84cc-41e5cdc23a19" --param microsoft_graph_fqdn="graph.microsoft.com" --param tfstate_container_name="tfstate" --param tfstate_resource_group_name="***" --param tfstate_storage_account_name="***" --param tre_id="***" --force --credential-set arm_auth --credential-set aad_auth

**Steps to reproduce**

1. Deploy tre at version 0.15.x
2. This error appears on the first run.
3. A rerun at this point fails with an error saying "Firewall Policy Rule Collection Group "rcg-core" already exists
4. login to azure, delete the "rcg-core" network collection
5. rerun successful

**Azure TRE release version 0.15.x:**

Believing that this is possibly a terraform ordering issue, "depends_on" has been added  to make the network collections dependent on the FW policy, and then subsequently then making the FW itself dependent on the network collection. This seemed to make matters worse so that attempted fix has been reverted.

**Comment by marrobi** [comment] 2023-11-06 09:35
Hi @Danny-Cooke-cCK. We have seen this before. I believe it is either the rule collection being created before the firewall policy is showing succeeded, or an Azure level failure with the deployment of the Firewall or Firewall Policy.  In your case I expect the former as rerunning succeeded.

Unless can reproduce it is hard to resolve... As a first step the Azure RM terraform provider in the Firewall Shared Service

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.53.0"
    }
  }

  backend "azurerm" {}
}
```

Looks like it could do with an update.

**Comment by Danny-Cooke-cCK** [comment] 2023-11-06 10:05
Thanks. This should be easy enough to recreate. it happens on every deployment we do for the first time. I'll get this fix in and test during this week and report back

**Comment by marrobi** [comment] 2023-11-06 10:07
Thanks strange as we don't see it in our extended tests, which are fresh deployments each time.

**Comment by Danny-Cooke-cCK** [comment] 2023-11-08 16:19
So a strange update on this. We spent the last few weeks running deployments with this issue occurring every time. After raising this ticket and making no changes at all, the problem has disappeared during two further deployments.  So i think we can close this as and underlying azure issue which seems to be rectified now? . Slightly annoying that it's disappeared as it was so consistently failing

**Comment by marrobi** [comment] 2023-11-08 17:36
If it comes back let us know. I've seen it before too, but very infrequently.

**Comment by jonnyry** [comment] 2023-11-08 22:46
We're getting something similar when the firewall shared service deploys:

![Capture](https://github.com/microsoft/AzureTRE/assets/7916532/8968fee7-1eaa-4732-97a0-9b7dd9966df2)

The initial message about the missing container image is not present in our log, but the remainder is the same.

**Comment by jonnyry** [comment] 2023-11-08 23:41
Possibly this? https://github.com/hashicorp/terraform-provider-azurerm/issues/15440

**Comment by marrobi** [comment] 2023-11-09 08:49
The missing container image can be ignored, docker returns that before needs to pull. We do try to  supress it in some places.

@jonnyry if look in the portal at the `Provisioning state` of the Firewall and the Firewall policy, what does it show? Do they show failed or succeeded?

![image](https://github.com/microsoft/AzureTRE/assets/17089773/2c113b2b-1f54-4f70-96a4-9c8de2b1f266)

**Comment by jonnyry** [comment] 2023-11-09 09:28
We have succeeded:

![Capture4](https://github.com/microsoft/AzureTRE/assets/7916532/6e26e5df-a61e-498c-a79b-88ba962c6723)

**Comment by marrobi** [comment] 2023-11-09 09:28
On both the firewall and the policy?

**Comment by jonnyry** [comment] 2023-11-09 09:29
Ah sorry, yes the policy has failed:

![Capture4](https://github.com/microsoft/AzureTRE/assets/7916532/3848b967-46cf-4d81-acca-a368da0702a4)

**Comment by marrobi** [comment] 2023-11-09 09:58
If you can - rather than just deleting and trying again (we know that will fix it if you need to move on now) it would be good to create a support case in the portal and ask for root cause as to why it has failed? Feel free to loop me into the email once get a support engineer - marcus.robinson at microsoft.com .

Unless you can see anything in the activity log on the resource? If any failures, please post the JSON output. Thanks.

**Comment by jonnyry** [comment] 2023-11-09 22:14
Sorry only just had chance to do a re-deploy (to a clean env)... same issue again (though this time I did get the "Unable to find image" error:

![Capture](https://github.com/microsoft/AzureTRE/assets/7916532/c0f0a4ef-c31d-4f62-a6c6-ae1b5a7be6a0)

Here's the Activity Log on the Firewall Policy:

![Capture2](https://github.com/microsoft/AzureTRE/assets/7916532/3b1c369d-0cfb-49df-a0ce-4703a0a4a8bc)

Here's the main failure I could see in the JSON on the activity log

```
    "properties": {
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"FirewallPolicyUpdateFailed\",\"message\":\"Put on Firewall Policy fw-policy-nwsdedev Failed with 1 faulted referenced firewalls\"}]}}",
```

When you say "deleting it and trying again" - do you mean just deleting the Firewall Policy in the Azure Portal and re-running the deploy?

**Comment by marrobi** [comment] 2023-11-10 09:22
Let me know if that works, in the meantime I'm going to try and find out if its an issue that has been seen elsewhere (outside of this project).

**Comment by jonnyry** [comment] 2023-11-10 10:08
Deleting the `rcg-core` rule collection and then re-running the failed job worked.

**Comment by Danny-Cooke-cCK** [comment] 2023-11-10 11:55
Thanks for your input @jonnyry. I haven't had time to investigate further on this but experience the same and like i said, i found it to be inconsistent failing sometimes and then working sometimes. 

to me the problem seems to be a dependency issue but then it fails with something completely different. What i was going to do next week is take the firewall code out separately, and run it in its own deployment just as terraform coe (removing the porter element from the equation) and seem if it fails like that. I'll report back when i've had chance

**Comment by marrobi** [comment] 2023-11-10 14:08
I wouldn't expect the Azure resource to be in a failed state as a result of a terraform dependency issue. Ultimately I think need to create a support case with the Azure team, with a failed deployment that they can look at.

**Comment by marrobi** [comment] 2023-11-10 14:44
I've been in touch with an engineering on the Azure Networking team. They would love some logs from Terraform with timestamps and correlation IDs.

To do this the the env var needs to be set: `TF_LOG="TRACE"`

@Danny-Cooke-cCK  You can see some shared services have a file to deploy locally already `templates/shared_services/gitea/terraform/deploy.sh`, if can create one of these for the firewall service and reproduce, it would be amazing. You can use `make terraform-deploy DIR=./templates/shared_services/firewall/terraform/`

**Comment by Danny-Cooke-cCK** [comment] 2023-11-10 14:46
ok cool. leave it with me. sounds like a monday job :)

**Comment by marrobi** [comment] 2023-11-10 14:51
Or even just the Azure resource ID -  such as  `/subscriptions/bb0916b2-xxxx-4efb-xxx-a41ecc9fd132/resourceGroups/rg-tre0db03523/providers/Microsoft.Network/firewallPolicies/fw-policy-tre0db03523` would be useful. Via Email or Teams.

**Comment by marrobi** [comment] 2023-11-14 16:09
Will return to this thread when have some further information. Azure team is investigating the operation logs.

**Comment by jonnyry** [comment] 2024-02-19 16:45
Hi @marrobi did you hear anymore from back from the Azure team?  We've just experienced this again on a fresh deployment cc @m1p1h

**Comment by marrobi** [comment] 2024-02-19 17:06
Can you create a support case via the portal and when you get a support engineer loop me in via email? It's not always the same thing.

My workaround it to delete `Firewall Policy Rule Collection Group "rcg-core"`, ensure the policy and Firewall are in a succeeded state and then run an upgrade on the firewall.

**Comment by jonnyry** [comment] 2024-02-21 10:36
Created supported case

**Comment by jonnyry** [comment] 2024-02-23 14:20
@marrobi sent you the log by email.

**Comment by marrobi** [comment] 2024-02-27 14:53
Thanks, awaiting product group feedback.

**Comment by jonnyry** [comment] 2024-02-27 15:12
Just to add that I've tried upgrading the Terraform `azurerm` provider version to the latest `3.93.0` and are still seeing the same error as above.

**Comment by marrobi** [comment] 2024-03-14 12:34
I've been thinking. We could move the firewall resource itself into the core deployment. Then just have the rules as the shared service. This would avoid these dependency issues and also potentially simplify deployment.

Could also have an env var in the `config.yaml` to specify firewall SKU, or even to not deploy the firewall at all for development sceanrios.

@tamirkamara welcome your thoughts on this.

**Comment by jonnyry** [comment] 2024-03-18 11:23
Hi @marrobi just wondering if you could help me understand where the firewall dependency issue lies -

I'm presuming it's not as simple as the firewall policy & the firewall being deployed at the same time - as these are both declared within https://github.com/microsoft/AzureTRE/blob/main/templates/shared_services/firewall/terraform/firewall.tf and I would hope terraform implicitly understands the dependency between these two.

Is it the fact that other shared services apply firewall rules, potentially at the same time / before the firewall & policy itself have been created?  (Since the firewall is a shared service itself & shared services are deployed concurrently in the Deploy TRE GitHub Action)

**Comment by marrobi** [comment] 2024-03-18 12:19
I believe the issue is the the terraform provider for the firewall is returning "success" before the deployment has actually finished. Hence the rules fail as are being associated with a Firewall that hasn't finished deploying. Other than having a pause, or loop to check, not something we can fix in the Azure TRE code base.

**Comment by marrobi** [comment] 2024-04-03 13:19
Ok, so it seems the firewall rule collections can't be applied if other operations on the subnets in the VNet are in progress.

 I suggest we try adding these dependencies to all of the route table associations ( https://github.com/microsoft/AzureTRE/blob/ddddbf6e3e8d13db477f70dc2ca8048dd12c563a/templates/shared_services/firewall/terraform/routetable.tf#L18-L52 )  along with `azurerm_firewall_policy_rule_collection_group.dynamic_network` and `azurerm_firewall_policy_rule_collection_group.dynamic_application`  so no subnets  on the vnet do not have any concurrent operations until after the firewall rules have deployed.

**Closed** 2024-04-04 10:35 UTC
Labels: bug
