### ISSUE TITLE
permission issue on home/vscode/.azure/config when running make all

### ISSUE THREAD

**Issue by chboudry** [microsoft/AzureTRE#1395] opened 2022-03-01 08:16 UTC
**Describe the bug**
On Windows, when you run make all, At one point you have the following error : 

The command failed with an unexpected error. Here is the traceback:
[Errno 1] Operation not permitted: '/home/vscode/.azure/config'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/config/custom.py", line 41, in config_set
    cmd.cli_ctx.config.set_value(section, name, _normalize_config_value(value))
  File "/opt/az/lib/python3.6/site-packages/knack/config.py", line 161, in set_value
    self._config_file_chain[-1].set_value(section, option, value)
  File "/opt/az/lib/python3.6/site-packages/knack/config.py", line 240, in set_value
    self.set(config)
  File "/opt/az/lib/python3.6/site-packages/knack/config.py", line 229, in set
    os.chmod(self.config_path, stat.S_IRUSR | stat.S_IWUSR)
PermissionError: [Errno 1] Operation not permitted: '/home/vscode/.azure/config'

**Steps to reproduce**

(issue occured on 2 unrelated env)

1. On Windows with WSL, follow tutorial steps
1. At "Make All" you have the issue above. 

**Analysis**

This is related to :
az config set extension.use_dynamic_install=yes_without_prompt 
in devops/scripts/control_tre.sh

Workaround was to : 
 1. run "sudo rm ~/.azure/commandIndex.json"  
 2. in control_tre.sh, replace the line with : **sudo** az config set extension.use_dynamic_install=yes_without_prompt
 3. run make all again

**Comment by marrobi** [comment] 2022-03-01 14:56
Wonder if this is the same as #1288, @chboudry  was this a fresh creation of the dev container? I rebuilt from clean yesterday and was fine. Wonder if its down to files already existing on WSL/Windows.

@ross-p-smith @stuartleeks any thoughts?

**Comment by chboudry** [comment] 2022-03-01 15:07
Customer encountered this issue yesterday, 
pretty sure it's related to WSL/Windows yes

**Comment by stuartleeks** [comment] 2022-03-02 09:40
Apologies - I've just spotted that you are running this inside the dev container. Could you run it again, but on the host in WSL?

**Comment by oliver7598** [comment] 2022-03-07 11:20
I've seen this issue before also and found this issue on the azure-cli repo which seems to suggest it arises from previously running an az command with `sudo`. [See here](https://github.com/Azure/azure-cli/issues/15638)

Removing the file highlighted in the error (`/home/vscode/.azure/config` in this case) should resolve the issue and allow the script to run as intended.

**Comment by stuartleeks** [comment] 2022-03-08 08:36
Thanks @oliver7598 . After some further discussion with @chboudry , it turned out that the repo was cloned and opened from the Windows file system. Re-cloning into WSL and opening from there seemed to resolve it.

**Comment by tamirkamara** [comment] 2022-05-29 13:26
Closing the issue since per the last few comments

**Comment by chboudry** [comment] 2022-08-08 10:53
Created a new TRE and stubble into this issue again.
You might want to update the documentation
so far for windows user, as per the doc, we clone the repo (from windows) and then open the dev container, so we are bound to have this issue

**Comment by sanjeevsidana** [comment] 2022-08-08 14:56
> @stuartleeks Created a new TRE and stubble into this issue again. You might want to update the documentation so far for windows user, as per the doc, we clone the repo (from windows) and then open the dev container, so we are bound to have this issue

I faced this same issue, but was able to resume the process as per steps by @oliver7598 . Thanks.
Something in the docs related to this would be really useful!

**Comment by marrobi** [comment] 2022-08-09 08:20
Reopening this, will add a clear comment to the docs. 

Also we will consider notifying users if they are running make commands from a repo cloned to windows.

**Closed** 2022-08-10 13:42 UTC
Labels: bug
