### ISSUE TITLE
 0 bytes data copied to Windows VM(guacamole RDP)

### ISSUE THREAD

**Issue by sanjeevsidana** [microsoft/AzureTRE#2455] opened 2022-08-12 15:18 UTC
Bug Description :

Copying file using we had a 0 bytes file after copying to Windows VM.
 
We tried with another file, and it is again 0 bytes. Though bottom right shows 28.8kb file transferred.

Refer to the screenshot attached.
![image](https://user-images.githubusercontent.com/24586771/184386294-9d447798-7fa1-43ba-8269-9a938b15559b.png)

 Could you please investigate this.? Thanks

**Steps to reproduce**

1. Create Windows workspace in TRE UI with attached shared storage.
2. Start RDP session using UI (Guacamole)
3. Upload a sample file to shared drive.
4. Open Shared drive and the file is shown as 0 bytes although in the bottom right it shows how many bytes git transferred.

**Comment by marrobi** [comment] 2022-08-12 21:43
@sanjeevsidana do you see anything in the browser console logs (dev tools)?

Thanks.

**Comment by marrobi** [comment] 2022-08-12 22:10
I've managed to reproduce it - not reliably - it took 10 attempts, but looking at the failed request I get a 404 and the tunnel is set to null, but on a successful upload it has a guid:
![image](https://user-images.githubusercontent.com/17089773/184450830-9782a656-d986-479c-831d-815eb6be489c.png)

I wonder if that's down to this issue - to be fixed in 1.6:

https://issues.apache.org/jira/browse/GUACAMOLE-1562

**Comment by marrobi** [comment] 2022-08-12 22:44
Ok, I've made some changes, the main one to pull the latest build (not part of a release) of Guacamole. For me it seems to be much better. 

It's not fit to be merged as is, but if you can give it a go - branch is at https://github.com/marrobi/AzureTRE/tree/marrobi/issue2455

If clone and build, publish, register the `templates/workspace_services/guacamole` and then deploy a new instance of the guacamole service in a new workspace see how you get on.

**Comment by marrobi** [comment] 2022-08-15 08:52
Discussion around when this fix will be released appears here - https://lists.apache.org/thread/t0bqttcbwrnqodgf4bn43kh4tncq1nwz

@tamirkamara @stuartleeks looks like might be a while before we see 1.6.0 - (1.5.0 is not available yet). Could pull the commit with the fix, but that would mean building from source.

Thoughts?

**Comment by marrobi** [comment] 2023-08-18 14:08
This was fixed in Guacamole 1.5.2 which is now being used.

**Closed by marrobi** 2023-08-18 14:08 UTC
Labels: bug
