### ISSUE TITLE
Manage TRE roles within the UI

### ISSUE THREAD

**Issue by chboudry** [microsoft/AzureTRE#2930] opened 2022-11-29 14:32 UTC
Customer would like for some end users to be able to add people into TRE roles within the UI, instead of having to do it in AAD on the Enterprise APP, or have to edit the AAD group.

**Comment by jjgriff93** [comment] 2022-11-29 23:39
Closing as duplicate of #2045

**Closed by jjgriff93** 2022-11-29 23:39 UTC
Labels: duplicate, feature
