### ISSUE TITLE
When running make tre-deploy in succession terraform updates/replaces resources that have not changed.

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#700] opened 2021-08-23 08:42 UTC
**Describe the bug**
Each time run make tre-deploy terraform updates/replaces resources unnecessarily.

**Steps to reproduce**

1. Deploy TRE with `make`
2. Re run `'make tre-deploy' and monitor terraform output.

**Comment by christoferlof** [comment] 2021-09-14 09:43
Possibly caused by policies changing resources after deployment?

**Comment by marrobi** [comment] 2022-01-11 21:17
Step one might be to flatten the terraform to remove the number of dependencies in each module.

**Comment by martinpeck** [comment] 2022-01-17 10:43
Examples of this:

- firewall gets deleted during deployment
- VM scalesets get deleted
- private endpoints get deleted

Suspect this is due to data resources in terraform.

Next steps:
- refactor scripts so that a plan can be easily run and compared with previous plan
- inspect TF files for obvious issues
- run multiple deployments

**Comment by marrobi** [comment] 2022-01-18 21:06
Here's an occurrence:

```
module.resource_processor_vmss_porter[0].azurerm_role_assignment.subscription_owner must be replaced
-/+ resource "azurerm_role_assignment" "subscription_owner" ***
      ~ id                               = "/subscriptions/***/providers/Microsoft.Authorization/roleAssignments/deb370d9-e9c0-6ede-a44b-1f1ee3d2146d" -> (known after apply)
      ~ name                             = "deb370d9-e9c0-6ede-a44b-1f1ee3d2146d" -> (known after apply)
      ~ principal_type                   = "ServicePrincipal" -> (known after apply)
      ~ role_definition_id               = "/subscriptions/***/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635" -> (known after apply)
      ~ scope                            = "/subscriptions/***" -> (known after apply) # forces replacement
      + skip_service_principal_aad_check = (known after apply)
        # (2 unchanged attributes hidden)
    ***
```

**Comment by marrobi** [comment] 2022-01-21 12:41
If look at the multiple attempts on this run various things are going on. The firewall was deleted even though it should have a lock on it.

https://github.com/microsoft/AzureTRE/runs/4895836850?check_suite_focus=true

**Comment by tanya-borisova** [comment] 2022-01-24 12:27
> Here's an occurrence:
> 
> ```
> module.resource_processor_vmss_porter[0].azurerm_role_assignment.subscription_owner must be replaced
> -/+ resource "azurerm_role_assignment" "subscription_owner" ***
>       ~ id                               = "/subscriptions/***/providers/Microsoft.Authorization/roleAssignments/deb370d9-e9c0-6ede-a44b-1f1ee3d2146d" -> (known after apply)
>       ~ name                             = "deb370d9-e9c0-6ede-a44b-1f1ee3d2146d" -> (known after apply)
>       ~ principal_type                   = "ServicePrincipal" -> (known after apply)
>       ~ role_definition_id               = "/subscriptions/***/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635" -> (known after apply)
>       ~ scope                            = "/subscriptions/***" -> (known after apply) # forces replacement
>       + skip_service_principal_aad_check = (known after apply)
>         # (2 unchanged attributes hidden)
>     ***
> ```

I've split out this bug into its own ticket: https://github.com/microsoft/AzureTRE/issues/1161

**Comment by tanya-borisova** [comment] 2022-01-26 11:27
I'm going to close this as the remaining work is tracked in https://github.com/microsoft/AzureTRE/issues/1161

**Closed by tanya-borisova** 2022-01-26 11:27 UTC
Labels: bug, size/M
