### ISSUE TITLE
"Name or service not known" when running > make firewall-install

### ISSUE THREAD

**Issue by kevinpagliarulo** [microsoft/AzureTRE#3133] opened 2023-01-27 16:33 UTC
"Name or service not known" when running `make firewall-install`

»»» 🧩  Registering /home/vscode/AzureTRE//templates/shared_services/firewall/ bundle...

╔══════════════════════════════════════╗
║          Azure TRE Makefile          ║
╚══════════════════════════════════════╝

»»» ✅ Checking pre-reqs...

Checking for Azure CLI...

Loading local environment variables...

Checking for Docker...

Checking for porter...
»»» 🔨 Azure details from logged on user 
»»»   • Subscription: Visual Studio Enterprise Subscription
»»»   • Tenant:       5000b353-9c2a-48a6-a362-ee4a92282390

Login Succeeded
CLI already signed in
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/httpcore-0.16.3-py3.8.egg/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.8/site-packages/httpcore-0.16.3-py3.8.egg/httpcore/backends/sync.py", line 94, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/httpx-0.23.3-py3.8.egg/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.8/site-packages/httpx-0.23.3-py3.8.egg/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.8/site-packages/httpcore-0.16.3-py3.8.egg/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/usr/local/lib/python3.8/site-packages/httpcore-0.16.3-py3.8.egg/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/usr/local/lib/python3.8/site-packages/httpcore-0.16.3-py3.8.egg/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/usr/local/lib/python3.8/site-packages/httpcore-0.16.3-py3.8.egg/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.8/site-packages/httpcore-0.16.3-py3.8.egg/httpcore/_sync/connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/httpcore-0.16.3-py3.8.egg/httpcore/backends/sync.py", line 94, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/httpcore-0.16.3-py3.8.egg/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/tre", line 33, in <module>
    sys.exit(load_entry_point('tre==0.1.2', 'console_scripts', 'tre')())
  File "/usr/local/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/tre-0.1.2-py3.8.egg/tre/commands/shared_service_templates/shared_service_template.py", line 38, in shared_service_template_show
    response = client.call_api(
  File "/usr/local/lib/python3.8/site-packages/tre-0.1.2-py3.8.egg/tre/api_client.py", line 101, in call_api
    response = client.request(method, f'{self.base_url}{url}', headers=headers, json=json_data, params=params)
  File "/usr/local/lib/python3.8/site-packages/httpx-0.23.3-py3.8.egg/httpx/_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.8/site-packages/httpx-0.23.3-py3.8.egg/httpx/_client.py", line 908, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.8/site-packages/httpx-0.23.3-py3.8.egg/httpx/_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.8/site-packages/httpx-0.23.3-py3.8.egg/httpx/_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.8/site-packages/httpx-0.23.3-py3.8.egg/httpx/_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.8/site-packages/httpx-0.23.3-py3.8.egg/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/httpx-0.23.3-py3.8.egg/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -2] Name or service not known
Error checking for existing template: 
make[1]: *** [/home/vscode/AzureTRE/Makefile:259: bundle-register] Error 1
make[1]: Leaving directory '/workspaces/AzureTRE-Commercial'
make: *** [/home/vscode/AzureTRE/Makefile:293: firewall-install] Error 2
@kevinpagliarulo ➜ /workspaces/AzureTRE-Commercial (main) $

**Comment by marrobi** [comment] 2023-01-27 16:52
I believe I have seen this if change TRE_ID. The TRE CLI caches the login.

The fix I have used is

`rm -rf /home/vscode/.config/tre/`

Then run make `firewall-install db-migrate show-core-output` which are the steps not yet run.

**Comment by tamirkamara** [comment] 2023-01-29 06:49
A duplicate of #3095

**Closed by tamirkamara** 2023-01-29 06:49 UTC
Labels: bug
