### ISSUE TITLE
[Story] Add API functionality to register a new user-resource template

### ISSUE THREAD

**Issue by adishachar** [microsoft/AzureTRE#482] opened 2021-07-20 14:13 UTC
## Description

**As a TRE Admin**
I want to be able to register a template for a new user-resource
so that TRE Researchers can add them to their workspaces

(a user-resource requires a specific workspace-service, ex. **Guacamole VM** that can be deployed in a **Guacamole Service**)

## Acceptance criteria

- [ ] **TRE Admin** can register a template by calling POST /api/service-templates/{template_name}/user-resource-templates -- with a workload like the following

```json
{
  "name": "guacamole-vm",
  "parentWorkspaceService": "guacamole-service",
  "version": "0.0.1",
  "current": "true",
  "json_schema": {
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://github.com/microsoft/AzureTRE/templates/workspaces/myworkspace/user-resource.json",
    "type": "object",
    "title": "My User-Resource Template Custom Parameters",
    "description": "These parameters are specific to my user-resource template",
    "required": ["vm_size"],
    "properties": {
      "vm_size": {
        "$id": "#/properties/vm_size",
        "type": "string",
        "title": "VM size",
        "description": "Size of the VM",
        "default": "Standard_A1",
        "enum": [
          "Standard_A1",
          "Standard_A2",
          "Standard_A3"        ]
      }
    }
  }
}
```

- [ ] Only admins can access the API
- [ ] Fails if same name/version already exists
- [ ] If current: true - sets this to current - and removes any previous current version
- [ ] Enriched user-resource schema is returned
- [ ] API is listed in swagger as register
- [ ] Swagger documentation, and post defaults apply to the template
- [ ] user-resource.json created

Technical Note:
- GET will be added in a separate story

**Comment by adishachar** [comment] 2021-08-03 13:33
@TessFerrandez 

- target resource service template --> definition of a specific resource. e.g. a dsvm or a vm 
- target resources service --> an instance of that template ---> actual resource. actual vm.
- Regarding the API and flow I would suggest to look at the Virtual Desktop ADR [https://dev.azure.com/CSECodeHub/429371%20-%20EFR%20-%20Azure%20TRE/_git/AzureTREResearch?path=%2Fdocs%2Farchitecture-decisions%2F010-Remote-Connectivity.md](url)
- in general registering a resource service template enables this resource service in the specific workspace, and then you can deploy a specific instance of it in this workspace. 
-  We agreed we will start with single specific target resource service template (DSVM), and expand to more resources in the future. The specification are taken from external resources (google). 
- As said in the definition for MVP we will focus on REGISTER and CREATE. We might need to add 'Get List' before adding a new template.

**Comment by TessFerrandez** [comment] 2021-08-03 14:52
@adishachar so am I understanding this correctly that this story is both about 

a) implementing the API for registering new services
b) implementing the API parts for adding the service to an existing VM and
c) implementing pieces in the deployment service to allow this...

that seems like a bit of a tall order for a one week story, we should probably split this into multiple more bite-size stories under a "service template" feature

**Comment by TessFerrandez** [comment] 2021-08-03 18:01
This also seems to be a duplicate of #500 or are they different?

**Comment by adishachar** [comment] 2021-08-04 07:36
it is not a duplicate.
this story is about API on the **target resource** service (vm, dsvm etc)
#500 is the story of API on the **workspace service** (azure ML etc)

**Closed** 2021-08-12 06:59 UTC
Labels: api, story, sprint candidate
