### ISSUE TITLE
Troubleshooting Slurm Workload Manager Deployment Steps

### ISSUE THREAD

**Issue by BiologyGeek** [microsoft/AzureTRE#4021] opened 2024-07-02 15:22 UTC
Hello team,

After resolving the Azure CycleCloud connectivity issue with subscription resources(https://github.com/microsoft/AzureTRE/issues/3933), a new problem is observed when attempting to run the Scheduler VM. Here is the error message:

![image](https://github.com/microsoft/AzureTRE/assets/157970993/9e8473ca-1c49-44ad-90dc-3410688cf4f7)

![image](https://github.com/microsoft/AzureTRE/assets/157970993/c093224c-7d0d-490b-ab13-9b7ff4d5b2d3)

Hint: During the Slurm setup, this Subnet ID was selected:
mytre: vnet-mytre-SharedSubnet [10.1.1.0/24]

![image](https://github.com/microsoft/AzureTRE/assets/157970993/d8afe45f-544b-4f03-803b-b451f46c9704)

I am wondering what could be the root cause of this issue?

**Comment by Danny-Cooke-CK** [comment] 2024-07-04 13:18
Hi @BiologyGeek. this looks still to be a network connection issue. "urllib2.URLError urlopen error errno 104 socket closed" also produces "connection reset by peer" typically. 

First route to check is the Firewall as the request is trying to reach a URL so is that in the firewall to start with. 
Secondly would look at NSG's and routing but i think this will be firewall related

**Comment by tim-allen-ck** [comment] 2024-07-09 09:28
> Thank you @Danny-Cooke-CK! I will go through checking these items, but my quick question is: Did I select the correct subnet ID during the selection process? It was `vnet-mytre-SharedSubnet [10.1.1.0/24]`.

Like Marcus said try using the `{tre}-ws-{id}-ServicesSubnet` 
Did you manage to get it working?

**Comment by PoojanumN** [comment] 2024-07-10 16:40
@tim-allen-ck can you please look into this ?

**Comment by tim-allen-ck** [comment] 2024-07-11 10:33
hi @BiologyGeek I'll have a look and give you an update by the end of the week.

**Comment by tim-allen-ck** [comment] 2024-07-16 16:20
Hi @BiologyGeek 
I've managed to get a node deployed through much trial and error.
There were a few things I did. 

- Changed the VM types to ones available in the quotas for my subscription. 
- Enabled `Allow Blob anonymous access` on the storage account used by the cluster. 
- Create the `cyclecloud` container with `Container` access level, in the storage account used by the cluster. 
- For testing, I opened up the firewall to allow everything in and out so that slurm could deploy.

Please give those a try and see how they work for you.

**Comment by tim-allen-ck** [comment] 2024-07-26 13:12
Hi @BiologyGeek, it looks like you have set up the firewall correctly. I created a PR with the updated tf code for the Firewall. #4040 
What size VMs are you deploying slurm with?

**Comment by marrobi** [comment] 2024-08-01 15:18
I've been looking into this for another scenario I am seeing traffic blocked outbound to locations such as `azcopyvnext.azureedge.net`. It looks like something has changed that means the cluster has external dependencies. Opening up this (azcopy) in the firewall is obviously a risk to data exfiltration.

Will have a dig and see if I can work out a way around it.

**Comment by marrobi** [comment] 2024-08-01 15:27
Reproduced the error on the cluster itself:
![image](https://github.com/user-attachments/assets/031ff358-f952-461c-93de-20bacea441c4)

**Comment by marrobi** [comment] 2024-08-01 16:37
Just sharing my work in progress, but getting further with using this as the init script, still working through issues:

```sh
#!/bin/sh
TRE_ID="mrtredemo2"
REGION="westeurope"

ls /etc/yum.repos.d/*.repo | xargs sed -i 's/mirrorlist/# mirrorlist/g'
ls /etc/yum.repos.d/*.repo | xargs sed -i "s,# baseurl=https://repo.almalinux.org/,baseurl=https://nexus-$TRE_ID.$REGION.cloudapp.azure.com/repository/almalinux/,g"

yum -y install epel-release
ls /etc/yum.repos.d/*.repo | xargs sed -i 's/metalink/# metalink/g'
ls /etc/yum.repos.d/*.repo | xargs sed -i "s,#baseurl=https://download.example/pub/epel/,baseurl=https://nexus-$TRE_ID.$REGION.cloudapp.azure.com/repository/fedoraproject/pub/epel/,g"

yum -y install python3 python3-pip

sudo tee /etc/pip.conf <<EOF
[global]
index = https://nexus-$TRE_ID.$REGION.cloudapp.azure.com/repository/pypi/pypi
index-url = https://nexus-$TRE_ID.$REGION.cloudapp.azure.com/repository/pypi/simple
trusted-host = https://nexus-$TRE_ID.$REGION.cloudapp.azure.com
EOF

sudo cat > /etc/yum.repos.d/cyclecloud.repo <<EOF
[cyclecloud]
name=cyclecloud
baseurl=https://nexus-$TRE_ID.$REGION.cloudapp.azure.com/repository/microsoft-yumrepos/cyclecloud
gpgcheck=1
gpgkey=https://nexus-$TRE_ID.$REGION.cloudapp.azure.com/repository/microsoft-keys/microsoft.asc
EOF

rpm --import https://nexus-$TRE_ID.$REGION.cloudapp.azure.com/repository/almalinux/almalinux/RPM-GPG-KEY-AlmaLinux
``

**Comment by marrobi** [comment] 2024-08-01 16:46
Can confirm that works:

![image](https://github.com/user-attachments/assets/5d8975f8-505e-48ba-bbd7-d03e7455aa53)

Will try to get a PR with this in tomorrow.

**Comment by marrobi** [comment] 2024-08-02 09:46
@BiologyGeek I've done this from scratch today and seemed to work fine. Can you try the new bundle in the PR and follow the docs steps, including updated init script.

If all works, then @tim-allen-ck suggest we get this merged as closes of a number of issues.

Thanks.

**Comment by marrobi** [comment] 2024-11-14 12:22
Closing this as not heard back.

**Closed by marrobi** 2024-11-14 12:22 UTC
Labels: question
