### ISSUE TITLE
AML Workspace service URL is incorrect

### ISSUE THREAD

**Issue by lenisha** [microsoft/AzureTRE#2549] opened 2022-09-05 20:09 UTC
URL created by AML Workspace service contains Unicode character that fails in navigation

**Steps to reproduce**

1. Create AML Workspace service
2.  Connection URI contains Unicode "\\u0026" instead of "&" sign, example:       "connection_uri": "https://ml.azure.com/?wsid=/subscriptions/xxxx/resourceGroups/rg-scctre-ws-579a/providers/Microsoft.MachineLearningServices/workspaces/ml-scctre-ws-579a-svc-28b0\\u0026tid=xxxxxx"

3. Navigation fails

**Comment by lenisha** [comment] 2022-09-07 06:58
Terraform output is correct @marrobi 
```

Apply complete! Resources: 11 added, 0 changed, 0 destroyed.

Outputs:

nection_uri = "https://ml.azure.com/?wsid=/subscriptions/*******/resourceGroups/rg-scctre-ws-935d/providers/Microsoft.MachineLearningServices/workspaces/m
l-scctre-ws-935d-svc-0cdf&tid=*******"
in
execution completed successfully!
```
But message in ServiceBus is already with incorrect Unicode for &

```
},
        {
            "Name": "connection_uri",
            "Value": "https://ml.azure.com/?wsid=/subscriptions/zzzz/resourceGroups/rg-scctre-ws-935d/providers/Microsoft.MachineLearningServices/workspaces/ml-scctre-ws-935d-svc-0cdf\\u0026tid=zzzzz",
            "Type": "string"
        },
        {
 
```

**Comment by marrobi** [comment] 2022-09-07 07:03
@lenisha thanks for tracking it down, It might be where JSON conversion is happening here: https://github.com/marrobi/AzureTRE/blob/6a4856e4843d2c778af48af5aec67f0e4d2854fe/resource_processor/vmss_porter/runner.py#L211

@damoodamoo any pointers as to how we can resolve this? Thanks.

**Comment by marrobi** [comment] 2022-09-07 07:15
Or it could be https://github.com/marrobi/AzureTRE/blob/marrobi/issue2480/resource_processor/vmss_porter/runner.py#L144

There is an `ensure_ascii=False` parameter for `json.dumps`.

**Comment by martinpeck** [comment] 2022-09-07 12:44
I'm not sure it's either of these things.
I suspect this is Terraform, and how it outputs are JSON formatted.

Here's my repo.

Create a minimal `main.tf`:

``` terraform
output "connection_uri" {
  value = "hello&world"
} 
```

Run `terraform apply` and you get the output:

``` text 
Outputs:

connection_uri = "hello&world"
```
This is correct. If you call `terraform output conection_uri` or even , t`terraform output -raw conection_uri` these are also both correct:

``` bash
$ terraform output connection_uri
"hello&world"
$ terraform output -raw connection_uri
hello&world
```

HOWEVER, if I use `terraform output -json connection_url`, getting a JSON representation of the outputs, the ampersand is then encoded. I suspect this is how Porter is accessing the outputs from Terraform:

``` bash
$ terraform output -json connection_uri
"hello\u0026world"
```
I suspect this is the place to start. This feels like an issue with the way that Terraform is formatting JSON output, combined with the fact that Porter is most likely accessing outputs in JSON format (which is not unreasonable). I'm digging around for bugs/issues in these repositories, but I'm not convinced this is a bug on our part (but it might be something we have to work around)

**Comment by martinpeck** [comment] 2022-09-07 13:09
This is confirmation that Porter's Terraform mix-in uses the -json flag:

``` golang
func (m *Mixin) getOutput(outputName string) ([]byte, error) {
	cmd := m.NewCommand("terraform", "output", "-json", outputName)
	cmd.Stderr = m.Err
```
https://github.com/getporter/terraform-mixin/blob/465b0462ce5d1d9f0abd7a5137084e1f87e959ac/pkg/terraform/terraform.go#L55

**Comment by martinpeck** [comment] 2022-09-07 13:15
It looks like this issue was raised against Terraform:
https://github.com/hashicorp/terraform/issues/26110

The fix was to better document it:
https://github.com/hashicorp/terraform/pull/26122

They don't intend to fix it...

> I think this 26110 since we're not going to change the behaviour.

**Comment by martinpeck** [comment] 2022-09-07 13:21
I suspect this means that this behaviour (broken URIs) has been present for some time.
Other than re-raising this issue with Terraform, or asking Porter to take on some patching/fixing of outputs to compensate, I suspect we'll have to deal with this within our own code by either...

1. constructing the URI ourselves by passing two separate outputs from terraform
2. decoding any URI ourselves by replacing the escaped ampersand with an actual ampersand

**Comment by marrobi** [comment] 2022-09-07 13:25
@martinpeck they work in general, I guess its just the query string that gets messed up. @lenisha what got lost/went wrong in the example you saw?

Re above 1  - can't see how that would work as could have any number of segments/

2. Feels more like a solution/ Can we use `.encode('utf-8')` to do this?

**Comment by martinpeck** [comment] 2022-09-07 13:30
Aha! This was changed in Porter 28 days ago...

https://github.com/getporter/terraform-mixin/commit/ebc5841afe5d6828eaf514813d530608bb80d3e5#diff-282757e263fe02ec96e35fd1120b9263db1ca315d75cea25d3ccf68239bd7472

Porter changed from raw to json output.

**Comment by martinpeck** [comment] 2022-09-07 13:31
I'll raise a bug on the Porter repo, explain what we're seeing etc.

**Comment by marrobi** [comment] 2022-09-07 13:32
@martinpeck great catch, explains why I hadn't seen it.

**Comment by marrobi** [comment] 2022-09-07 13:33
Wonder if we can pin the mixin to a specific release?

**Comment by martinpeck** [comment] 2022-09-07 13:45
I've raised issue https://github.com/getporter/terraform-mixin/issues/94

**Comment by lenisha** [comment] 2022-09-07 15:22
Is there a workaround for us in interim to make AML Connect URL work?

**Comment by martinpeck** [comment] 2022-09-07 15:24
Not an obvious one. How are you using that URL?
Are you clicking on it from a web page, or consuming it in some other way?

**Comment by tamirkamara** [comment] 2022-09-07 15:28
@martinpeck, @lenisha how about an `exec` step after the terraform one to take the malformed terraform value (output) and generating a new correct output that will be used as the bundle level output (which then will be used in the UI)?

**Comment by marrobi** [comment] 2022-09-07 16:15
@lenisha it might be you don't need the tenant id in your case - this was to catch an issue when a user has multiple tenants with differing conditional access policies. You could modify the terraform in your AML bundle to get right of the & and beyond.

**Comment by martinpeck** [comment] 2022-09-07 16:33
Yeah, if you're able to modify your bundle there are options (remove the `tid` querystring param, or base64 encode the value in terraform then decode outside, or use urlencode in terrraform then urldecode outside). None of these are great as they don't fix the problem of other outputs containing ampersands, or the other characters that Terraform encodes.

I'd hope, longer term, we can take an upstream fix (in Porter mixin, for example).

**Comment by lenisha** [comment] 2022-09-07 22:40
yep added encode/decode to the mixin pipelines as a workaround for now - it works, commit:
https://github.com/lenisha/AzureTRE/commit/c610b33547d049b38867844a00306aa784ffb85c 
@marrobi  @martinpeck

**Comment by marrobi** [comment] 2022-09-22 19:05
@martinpeck I've been trying to work out if this fix has made it into porter as think we've hit it again today. Not sure how the mixin releases relate to the Porter releases. See https://github.com/getporter/porter/releases/tag/v0.38.13 for the latest 0.x release. 

We should probably create an issue to start looking at v1.0 of porter too.

**Comment by marrobi** [comment] 2022-09-22 19:11
So we are using v0.38.12 of Porter, do we need to go to v1.0.0-rc.1 of Porter to get this mixin update? I don't think that will be straightforward.

**Comment by marrobi** [comment] 2022-09-22 19:13
Or can we manually install the mixin in the dev container and RP image using `porter mixin install terraform` ?

**Comment by martinpeck** [comment] 2022-09-22 19:13
I don't know, but I don't think so.

I thought porter picked up the latest mixins (which is why the regression was seen).

**Comment by tamirkamara** [comment] 2022-09-22 19:38
The mixin wasn't released yet

**Comment by marrobi** [comment] 2022-09-22 19:39
I rebuilt the dev container without cache and got 

```
vscode ➜ ~/.porter/mixins/terraform/runtimes $ ./terraform-runtime version
terraform v0.10.0 (465b046) by Porter Authors
```

Which is from August - https://github.com/getporter/terraform-mixin/releases/tag/v0.10.0

Will try upgrading the porter version.

**Comment by martinpeck** [comment] 2022-09-22 19:40
> The mixin wasn't released yet

How do you mean? the RC was released in the last 22 hours

**Comment by tamirkamara** [comment] 2022-09-22 19:41
> > The mixin wasn't released yet
> 
> How do you mean? the RC was released in the last 22 hours

Right, my page apparently needed refreshing :-)

**Comment by marrobi** [comment] 2022-09-22 19:44
No luck:
```
vscode ➜ ~/.porter/mixins/terraform/runtimes $ porter --version
porter v0.38.13 (85b77f62)
vscode ➜ ~/.porter/mixins/terraform/runtimes $ ./terraform-runtime version
terraform v0.10.0 (465b046) by Porter Authors
```

**Comment by marrobi** [comment] 2022-09-22 19:46
This works though:
```
vscode ➜ ~/.porter/mixins/terraform/runtimes $ porter mixins install terraform
installed terraform mixin v0.10.0 (465b046)
vscode ➜ ~/.porter/mixins/terraform/runtimes $ porter mixin install terraform --version v1.0.0-rc.1
installed terraform mixin v1.0.0-rc.1 (090064b)
vscode ➜ ~/.porter/mixins/terraform/runtimes $ ./terraform-runtime version
terraform v1.0.0-rc.1 (090064b) by Porter Authors
```

**Comment by martinpeck** [comment] 2022-09-22 19:47
See: https://github.com/getporter/terraform-mixin/issues/94#issuecomment-1255472603

**Comment by marrobi** [comment] 2022-09-22 20:21
@martinpeck we install the mixins here: `.devcontainer/scripts/porter.sh` and use `latest`, which is from April.

**Comment by martinpeck** [comment] 2022-09-22 20:24
Ah! I was looking for that but couldn't find it!

**Closed** 2022-09-22 22:00 UTC
Labels: bug
