### ISSUE TITLE
Creating resource bundles within a template

### ISSUE THREAD

**Issue by v-smahaj** [microsoft/AzureTRE#3098] opened 2023-01-20 02:29 UTC
Currently, we can create resources from available list using template. 
How can we create resource bundles in a single template:
Example: 
Bundle 1: Virtual Machine with R
Bundle 2: Virtual Machine with SQL Server

**Comment by tamirkamara** [comment] 2023-02-02 15:16
Perhaps this is a terminology difference but if you can create one template with multiple resource in it.
Or, do you mean that you have 2 separate templates that you wish to group somehow together so that with one create request the system would handle all the underlining sub templates?

**Comment by MahajanSaurabh92** [comment] 2023-02-09 21:14
Yes
I wish to have group of resources inside a template so that if I create group 1 then all the resources in group 1 are created.
1 level of parent child relationship inside templates.

**Comment by marrobi** [comment] 2023-03-08 11:01
@v-smahaj @MahajanSaurabh92 believe is this a duplicate of https://github.com/microsoft/AzureTRE/issues/2550 ?

Will close this issue unless you believe otherwise.

**Closed by marrobi** 2023-03-08 11:01 UTC
Labels: feature
